#pragma once
#include<iostream>
#include"Tape.h"
#include<fstream>
#include<string>
#include<cstdio>
#include<tuple>
#include <algorithm>
#include <iomanip>

using namespace std;

const string filename = "tapes.dat";

tuple<Tape*, int> readTapeFile() {
	ifstream file;
	file.open(filename, ios::binary);
	if (!file) {
		cout << "File doesn't exist, creating a new file.\n";
		fstream f;
		f.open(filename, fstream::in | fstream::out | fstream::trunc);
		f.close();
		Tape* t = new Tape[0];
		return make_tuple(t, 0);
	}
	else {
		file.seekg(0, ios::end);
		int tapeSize = file.tellg(); 
		tapeSize = tapeSize / sizeof(Tape);
		file.seekg(0, ios::beg);

		Tape* tapes = new Tape[tapeSize];
		file.read((char*)tapes, tapeSize * sizeof(Tape));
		file.close();
		cout << endl;

		return make_tuple(tapes, tapeSize);
	}	
};

void writeTapeFile(struct Tape *tape) {
	ofstream file;
	file.open(filename, ios::binary | ios::app);

	if (!file) {
		cout << "File could not be loaded\n";
	}
	else {
		file.write((char*)tape, sizeof(Tape));		
	}
	file.close();
}

void truncateTapeFile() {
	ofstream file;
	file.open("tapes.dat", ios::binary | ios::trunc);
	file.close();
}

//SHOW ALL AVAILABLE TAPES
void showAllTape() {
	Tape* tapes; 
	int tapesSize; 
	int tapeIdSize = 0;
	int longestTitle = 0;
	int amountSize = 0;
	int hBorderSize = 0;
	string hBorder;
	string separator = " | ";
	string tapeID = separator + "Tape ID";
	string title = separator + "Title";
	string amount = separator + "Ammount |";
	
	tie(tapes, tapesSize) = readTapeFile();

	// Get sizes to construct table
	tapeIdSize = tapeID.size() - separator.size();
	for (int i = 0; i < tapesSize; i++) {
		string tmp(tapes[i].title);
		longestTitle = tmp.size() > longestTitle ? tmp.size() : longestTitle;
	}
	amountSize = amount.size();
	
	hBorderSize = tapeIdSize + longestTitle + amountSize + separator.size();
	hBorder.append(hBorderSize, '_');

	// Build table
	cout << "  " << hBorder << endl;
	cout << setw(tapeIdSize) << left << tapeID
		 << setw(longestTitle + separator.size()) << title  << left
		 << setw(amountSize) << left << amount  << endl;
	cout << "  " << hBorder << endl;
	// Show stock
	for (int i = 0; i < tapesSize; i++) {
		cout << separator << setw(tapeIdSize) << left << tapes[i].ID
			 << separator << setw(longestTitle) << left << tapes[i].title
			 << separator << setw(amountSize - separator.size() -1) << left << tapes[i].ammount << "|" << endl;
	}
	cout << "  " << hBorder << endl << endl;

	system("pause");
};

//ADD NEW TAPE WITH AUTOGENERATED ID
void addNewTape() {
	int newID = -1;
	int tapesSize;
	auto newTape = new Tape[1];	
	Tape* tapes;
	bool sortById = false;
	
	// Auto generate ID	
	tie(tapes, tapesSize) = readTapeFile();	
	if (tapesSize == 0) { newID = 1; }
	else if (tapesSize == 1) { newID = tapes[0].ID + 1; }

	// Fill ID "holes" if any
	for (int i = 0; i < tapesSize - 1; i++) {		
		if (tapes[i].ID + 1 != tapes[i + 1].ID) { newID = tapes[i].ID + 1; sortById = true; }
	}
	// If no "holes" make new ID
	if (newID == -1) { newID = tapes[tapesSize - 1].ID + 1; }	

	// Get input
	string tmpName;
	newTape->ID = newID;
	cout << "Enter the title of the tape: ";		
	getline(cin >> ws, tmpName);
	strcpy(newTape->title, tmpName.c_str());
	cout << "Enter ammount: "; cin >> newTape->ammount;
	
	// Save to file
	if (!sortById) {
		writeTapeFile(newTape);
		system("cls");
		cout << "New title: \"" << newTape->title << "\" added to the database." << endl;
	}
	else {
		truncateTapeFile();
		for (int i = 0; i < tapesSize; i++) {
			for (int j = 0; j < tapesSize; j++) {
				if (tapes[j].ID - 1 == i) {
					writeTapeFile(&tapes[j]);
				}
				else if (newTape->ID - 1 == i) {
					writeTapeFile(newTape);
				}
			}
		}
	}

	delete[]newTape;	
	system("pause");
};

//DELETE ANY TAPE
void deleteTape() {
	int ID;
	int choice = 0;
	int tapesSize;
	Tape *tapes;
	bool deleteTape = false;

	tie(tapes, tapesSize) = readTapeFile();
	showAllTape();
		
	cout << "Enter ID of the tape you want to delete: "; cin >> ID;

	for (int i = 0; i < tapesSize; i++) {
		if (tapes[i].ID == ID) {
			cout << "Tape ID: " << tapes[i].ID << " * Title: " << tapes[i].title << endl;
			cout << "Delete this tape?\n1. Yes\n2. No\nOption: "; cin >> choice;
			deleteTape = choice == 1 ? true : false;
		}
	}

	if (deleteTape) {
		truncateTapeFile();
		for (int i = 0; i < tapesSize; i++) {
			if (tapes[i].ID != ID) {
				writeTapeFile(&tapes[i]);
			}
		}	
	}

	cout << "Deleted";
	showAllTape();
};